"use client";

import { useState } from "react";

import { ToolBreadcrumb } from "@/components/tools/tool-breadcrumb";
import { Checkbox } from "@/components/ui/checkbox";
import { MaterialIcon } from "@/components/ui/material-icon";
import { secureRandomInt, secureRandomIntInRange } from "@/lib/random";
import { getToolBySlug } from "@/lib/tools/registry";

const tool = getToolBySlug("random-number-generator")!;

/**
 * Hand-transcribed verbatim from the Stitch "Random Number Generator" HTML
 * export the user pasted directly (same literal-HTML process as Home/Unit
 * Converter/UUID Generator — see docs/PLAN.md #6/#7/#8) — centered header,
 * 3-column bento (Configuration + Result), two-column "How It
 * Works"/"Uses for Random Numbers" section, and a centered FAQ with its own
 * bordered-card styling. None of that fits ToolPageShell's standard
 * left-aligned wrapper, so `layout: "custom"` in the registry, same
 * treatment as the other hand-transcribed tools.
 *
 * Breadcrumb added after launch (2026-08-09) — see AttendanceCalculatorTool
 * for why (was "centered no-breadcrumb header" originally). Wrapped in
 * `flex justify-center` to match this page's centered layout.
 *
 * Color/radius classes are this site's existing tokens, not Stitch's raw
 * hex/scale: surface-container-lowest → card, outline-variant → border,
 * on-surface-variant → muted-foreground, its `bg-[#FAFAFA]` input fill →
 * our --input token (already that exact value), its "lg" radius (8px) →
 * our rounded-md, its DEFAULT radius (4px) → our rounded-sm. The Generate
 * button's `hover:bg-surface-tint` (Stitch's literal, one-off hover hex,
 * `#0059c5`) isn't a token this project reuses anywhere else — mapped to
 * the same `hover:bg-primary-hover` every other primary button on this site
 * already uses instead of introducing a single-use token for a near-
 * identical shade.
 *
 * Two behavior changes from the tool's own previous version, both from
 * Stitch's design itself rather than an editorial choice:
 *  - **Default is now unique, not duplicate-allowing.** The old UI defaulted
 *    to "duplicates allowed" with an opt-in "No duplicates" checkbox; this
 *    design defaults to unique (no duplicates) with an opt-in "Allow
 *    duplicates" checkbox — the two checkboxes are inverses of each other,
 *    and Stitch's own default state (both boxes unchecked) means unique.
 *  - **Max quantity is 10,000, not 1,000** — matches the input's own `max`
 *    attribute and the FAQ's own copy ("we limit single batches to 10,000
 *    numbers").
 * New: an explicit "Sort results" option, which the old version didn't have.
 *
 * Not reproduced: Stitch's mockup shows a static "42" in the Result panel
 * on load, since it's a design mockup rather than live JS. Starts empty
 * with a "Click Generate" placeholder instead, same call (and same
 * set-state-in-effect lint reasoning) as UuidGeneratorTool.
 */

const FAQ_ITEMS = [
  {
    question: "Are the numbers truly random?",
    answer:
      "They are pseudo-random, meaning they are generated by a deterministic algorithm initialized with an unpredictable seed. For almost all practical, non-highly-classified purposes, they are sufficiently random.",
  },
  {
    question: "Is there a limit to how many I can generate?",
    answer:
      "To maintain browser performance, we limit single batches to 10,000 numbers. You can generate multiple batches if needed.",
  },
];

const MAX_QUANTITY = 10000;

function generateNumbers(min: number, max: number, count: number, allowDuplicates: boolean): number[] {
  if (allowDuplicates) {
    return Array.from({ length: count }, () => secureRandomIntInRange(min, max));
  }
  const rangeSize = max - min + 1;
  const pool = Array.from({ length: rangeSize }, (_, i) => min + i);
  const take = Math.min(count, rangeSize);
  // Partial Fisher-Yates: only shuffle as many positions as we need.
  for (let i = 0; i < take; i++) {
    const j = i + secureRandomInt(pool.length - i);
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, take);
}

export function RandomNumberGeneratorTool() {
  const [min, setMin] = useState(1);
  const [max, setMax] = useState(100);
  const [count, setCount] = useState(1);
  const [allowDuplicates, setAllowDuplicates] = useState(false);
  const [sortResults, setSortResults] = useState(false);
  const [numbers, setNumbers] = useState<number[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  function handleGenerate() {
    if (min > max) {
      setError("Min must be less than or equal to max.");
      return;
    }
    const rangeSize = max - min + 1;
    const safeCount = Math.max(1, Math.min(MAX_QUANTITY, count));
    if (!allowDuplicates && safeCount > rangeSize) {
      setError(`Only ${rangeSize} unique number${rangeSize === 1 ? "" : "s"} are possible in that range.`);
      return;
    }
    setError(null);
    const result = generateNumbers(min, max, safeCount, allowDuplicates);
    setNumbers(sortResults ? [...result].sort((a, b) => a - b) : result);
    setCopied(false);
  }

  function handleClear() {
    setNumbers([]);
    setError(null);
    setCopied(false);
  }

  async function handleCopy() {
    if (!numbers.length) return;
    await navigator.clipboard.writeText(numbers.join(", "));
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    // A plain <div>, not <main> — RootLayout already provides the page's
    // one <main> landmark; this "custom layout" component renders inside
    // it (see ToolPageShell), so a second <main> here would be invalid.
    <div className="mx-auto flex max-w-[1200px] flex-col gap-16 px-4 py-12 md:px-10 md:py-24">
      {/* Tool Header */}
      <div className="space-y-4 text-center">
        <div className="flex justify-center">
          <ToolBreadcrumb tool={tool} />
        </div>
        <h1 className="text-headline-lg text-foreground">Random Number Generator</h1>
        <p className="mx-auto max-w-2xl text-body-lg text-muted-foreground">
          Generate a sequence of random numbers within a specified range. Fast, free, and secure.
        </p>
      </div>

      {/* Tool Layout (Bento Grid Style) */}
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        {/* Input Controls Card */}
        <div className="flex flex-col gap-6 rounded-md border border-border bg-card p-6 lg:col-span-1">
          <div className="border-b border-border pb-4">
            <h2 className="text-headline-md text-foreground">Configuration</h2>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-2">
              <label htmlFor="min-num" className="text-label-sm text-muted-foreground">
                Min
              </label>
              <input
                id="min-num"
                type="number"
                value={min}
                onChange={(event) => setMin(Number(event.target.value))}
                className="w-full rounded-sm border border-border bg-input px-3 py-2 font-mono text-sm text-foreground focus:border-primary focus:ring-2 focus:ring-primary focus:outline-none"
              />
            </div>
            <div className="flex flex-col gap-2">
              <label htmlFor="max-num" className="text-label-sm text-muted-foreground">
                Max
              </label>
              <input
                id="max-num"
                type="number"
                value={max}
                onChange={(event) => setMax(Number(event.target.value))}
                className="w-full rounded-sm border border-border bg-input px-3 py-2 font-mono text-sm text-foreground focus:border-primary focus:ring-2 focus:ring-primary focus:outline-none"
              />
            </div>
          </div>
          <div className="flex flex-col gap-2">
            <label htmlFor="count-num" className="text-label-sm text-muted-foreground">
              Quantity
            </label>
            <input
              id="count-num"
              type="number"
              min={1}
              max={MAX_QUANTITY}
              value={count}
              onChange={(event) => setCount(Number(event.target.value))}
              className="w-full rounded-sm border border-border bg-input px-3 py-2 font-mono text-sm text-foreground focus:border-primary focus:ring-2 focus:ring-primary focus:outline-none"
            />
          </div>
          <div className="flex flex-col gap-4">
            <Checkbox
              id="allow-duplicates"
              label="Allow duplicates"
              checked={allowDuplicates}
              onChange={(event) => setAllowDuplicates(event.target.checked)}
            />
            <Checkbox
              id="sort-results"
              label="Sort results"
              checked={sortResults}
              onChange={(event) => setSortResults(event.target.checked)}
            />
          </div>
          {error && (
            <p role="alert" className="text-body-md text-destructive">
              {error}
            </p>
          )}
          <div className="mt-auto border-t border-border pt-6">
            <button
              type="button"
              onClick={handleGenerate}
              className="flex w-full items-center justify-center gap-2 rounded-sm bg-primary-button py-3 text-label-sm text-primary-foreground transition-colors hover:bg-primary-hover"
            >
              <MaterialIcon name="casino" className="text-lg" />
              Generate
            </button>
          </div>
        </div>

        {/* Output Display Card */}
        <div className="relative flex h-[400px] flex-col rounded-md border border-border bg-card p-6 lg:col-span-2">
          <div className="mb-4 flex items-center justify-between border-b border-border pb-4">
            <h2 className="text-headline-md text-foreground">Result</h2>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={handleClear}
                aria-label="Clear"
                className="flex items-center justify-center rounded-sm border border-border bg-background p-2 text-muted-foreground transition-colors hover:bg-surface-low"
              >
                <MaterialIcon name="delete" className="text-sm" />
              </button>
              <button
                type="button"
                onClick={handleCopy}
                aria-label="Copy"
                className="flex items-center justify-center rounded-sm border border-border bg-background p-2 text-muted-foreground transition-colors hover:bg-surface-low"
              >
                <MaterialIcon name={copied ? "check" : "content_copy"} className="text-sm" />
              </button>
            </div>
          </div>
          <div className="relative flex flex-grow items-center justify-center overflow-auto rounded-sm bg-[#111] p-6 text-muted-foreground">
            <div className="w-full text-center leading-relaxed break-all">
              {numbers.length ? (
                <span className="font-mono text-sm text-white">{numbers.join(", ")}</span>
              ) : (
                // text-gray-400, not -500 (2026-08-09, Phase B): -500 was
                // 3.91:1 against this fixed bg-[#111], short of 4.5:1.
                <span className="font-mono text-sm text-gray-400">Click Generate to create numbers.</span>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* SEO Content Section */}
      <section className="flex flex-col gap-12">
        <div className="grid grid-cols-1 gap-12 md:grid-cols-2">
          <div className="flex flex-col gap-4">
            <h3 className="text-headline-md text-foreground">How It Works</h3>
            <p className="text-muted-foreground">
              Our random number generator utilizes cryptographically secure pseudo-random number generation (CSPRNG)
              algorithms provided by the modern web browser environment. This ensures that the numbers produced are
              unpredictable and statistically sound for most general applications, unlike older Math.random()
              implementations.
            </p>
          </div>
          <div className="flex flex-col gap-4">
            <h3 className="text-headline-md text-foreground">Uses for Random Numbers</h3>
            <ul className="list-inside list-disc space-y-2 text-muted-foreground">
              <li>Statistical sampling and data analysis</li>
              <li>Gaming, simulations, and procedural generation</li>
              <li>Contest drawings and sweepstakes winners</li>
              <li>Generating secure temporary PINs or tokens</li>
              <li>Educational demonstrations of probability</li>
            </ul>
          </div>
        </div>

        {/* FAQ */}
        <div className="flex flex-col gap-6">
          <h3 className="text-center text-headline-md text-foreground">Frequently Asked Questions</h3>
          <div className="mx-auto flex w-full max-w-3xl flex-col gap-4">
            {FAQ_ITEMS.map((item) => (
              <div key={item.question} className="rounded-sm border border-border bg-card p-4">
                <h4 className="mb-2 text-label-sm font-medium text-foreground">{item.question}</h4>
                <p className="text-sm text-muted-foreground">{item.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}
